# Generated by Django 3.1 on 2020-09-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200927_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ban_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
