# Generated by Django 3.1 on 2020-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200927_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ban_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
