# Generated by Django 3.1 on 2020-10-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201014_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lateness_ago',
        ),
    ]
