# Generated by Django 3.1 on 2020-09-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200918_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='lateness_benchmark',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='time_in',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='time_out',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
